### PR TITLE
Improve and simplify buildsystem, and add support for python 3.x

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by ljod** [comment]
Thanks very much JC!!! We will have time to look at all these great changes and merge next week.

**Comment by jcfr** [comment]
I will have associated python3 fix shortly

**Comment by jcfr** [comment]
This is almost ready for final QA. 

It turns out that using `SampleData.downloadFromURL()` function lead to the creation of a node named `tract1_1` where nodename is specified as `tract1`.

**Comment by jcfr** [comment]
All tests now pass when building against the latest Slicer 4.11 r28156. 

Changes are expected to be compatible with Slicer 4.10, once integrated dashboard will confirm this.

```
$ ctest -j4
Test project /home/jcfr/Projects/SlicerDMRI-build/inner-build
      Start 46: FiberBundleLabelSelectTestVTP
      Start 44: FiberBundleLabelSelectTestVTK
      Start 36: FiberTractMeasurementsTestHierarchy
      Start 35: FiberTractMeasurementsTestFolder
 1/54 Test #36: FiberTractMeasurementsTestHierarchy ...................................   Passed    0.31 sec
 2/54 Test #35: FiberTractMeasurementsTestFolder ......................................   Passed    0.30 sec
      Start  1: qSlicerTractographyDisplayModuleGenericTest
      Start  3: qSlicerTractographyDisplayGlyphWidgetTest1
 3/54 Test #46: FiberBundleLabelSelectTestVTP .........................................   Passed    0.41 sec
 4/54 Test #44: FiberBundleLabelSelectTestVTK .........................................   Passed    0.41 sec
      Start  2: qSlicerTractographyDisplayModuleWidgetGenericTest
      Start 16: qSlicerTractographyInteractiveSeedingModuleWidgetGenericTest
 5/54 Test  #3: qSlicerTractographyDisplayGlyphWidgetTest1 ............................   Passed    1.00 sec
      Start 18: qSlicerTractographyInteractiveSeedingModuleWidgetTest2
 6/54 Test  #1: qSlicerTractographyDisplayModuleGenericTest ...........................   Passed    1.62 sec
      Start 17: qSlicerTractographyInteractiveSeedingModuleWidgetTest1
 7/54 Test #16: qSlicerTractographyInteractiveSeedingModuleWidgetGenericTest ..........   Passed    5.32 sec
      Start 15: qSlicerTractographyInteractiveSeedingModuleGenericTest
 8/54 Test #17: qSlicerTractographyInteractiveSeedingModuleWidgetTest1 ................   Passed    3.91 sec
 9/54 Test #18: qSlicerTractographyInteractiveSeedingModuleWidgetTest2 ................   Passed    4.25 sec
      Start 48: ExtractDWIShells_Test
      Start 22: DiffusionTensorScalarMeasurementsTestDeterminant
10/54 Test  #2: qSlicerTractographyDisplayModuleWidgetGenericTest .....................   Passed    5.76 sec
      Start 28: DiffusionTensorScalarMeasurementsTestSphericalMeasure
11/54 Test #22: DiffusionTensorScalarMeasurementsTestDeterminant ......................   Passed    0.36 sec
      Start 23: DiffusionTensorScalarMeasurementsTestRelativeAnisotropy
12/54 Test #28: DiffusionTensorScalarMeasurementsTestSphericalMeasure .................   Passed    0.56 sec
      Start 20: DiffusionWeightedVolumeMaskingTest
13/54 Test #23: DiffusionTensorScalarMeasurementsTestRelativeAnisotropy ...............   Passed    0.70 sec
14/54 Test #20: DiffusionWeightedVolumeMaskingTest ....................................   Passed    0.50 sec
      Start 34: DiffusionTensorScalarMeasurementsTestMeanDiffusivity
      Start 33: DiffusionTensorScalarMeasurementsTestPerpendicularDiffusivity
15/54 Test #33: DiffusionTensorScalarMeasurementsTestPerpendicularDiffusivity .........   Passed    0.40 sec
16/54 Test #48: ExtractDWIShells_Test .................................................   Passed    2.01 sec
17/54 Test #34: DiffusionTensorScalarMeasurementsTestMeanDiffusivity ..................   Passed    0.45 sec
      Start 24: DiffusionTensorScalarMeasurementsTestFractionalAnisotropy
      Start 30: DiffusionTensorScalarMeasurementsTestMidEigenvalue
      Start 32: DiffusionTensorScalarMeasurementsTestParallelDiffusivity
18/54 Test #32: DiffusionTensorScalarMeasurementsTestParallelDiffusivity ..............   Passed    0.40 sec
19/54 Test #24: DiffusionTensorScalarMeasurementsTestFractionalAnisotropy .............   Passed    0.49 sec
20/54 Test #30: DiffusionTensorScalarMeasurementsTestMidEigenvalue ....................   Passed    0.58 sec
      Start 27: DiffusionTensorScalarMeasurementsTestPlanarMeasure
      Start 37: FiberTractMeasurementsTestHierarchyAllStatistics
      Start 31: DiffusionTensorScalarMeasurementsTestMaxEigenvalue
21/54 Test #37: FiberTractMeasurementsTestHierarchyAllStatistics ......................   Passed    0.29 sec
22/54 Test #31: DiffusionTensorScalarMeasurementsTestMaxEigenvalue ....................   Passed    0.35 sec
      Start 43: TractographyLabelMapSeedingTest
      Start 21: DiffusionTensorScalarMeasurementsTestTrace
23/54 Test #27: DiffusionTensorScalarMeasurementsTestPlanarMeasure ....................   Passed    0.41 sec
24/54 Test #43: TractographyLabelMapSeedingTest .......................................   Passed    0.36 sec
      Start 25: DiffusionTensorScalarMeasurementsTestMode
      Start 26: DiffusionTensorScalarMeasurementsTestLinearMeasure
25/54 Test #21: DiffusionTensorScalarMeasurementsTestTrace ............................   Passed    0.66 sec
      Start 29: DiffusionTensorScalarMeasurementsTestMinEigenvalue
26/54 Test #25: DiffusionTensorScalarMeasurementsTestMode .............................   Passed    0.32 sec
27/54 Test #26: DiffusionTensorScalarMeasurementsTestLinearMeasure ....................   Passed    0.32 sec
      Start  7: vtkMRMLFiberBundleNodeTest1
      Start  4: vtkMRMLFiberBundleDisplayNodeTest1
28/54 Test  #4: vtkMRMLFiberBundleDisplayNodeTest1 ....................................   Passed    0.24 sec
29/54 Test #29: DiffusionTensorScalarMeasurementsTestMinEigenvalue ....................   Passed    0.46 sec
      Start  6: vtkMRMLFiberBundleLineDisplayNodeTest1
      Start 19: DWIToDTIEstimationTest
30/54 Test  #7: vtkMRMLFiberBundleNodeTest1 ...........................................   Passed    0.34 sec
31/54 Test  #6: vtkMRMLFiberBundleLineDisplayNodeTest1 ................................   Passed    0.20 sec
      Start  8: vtkMRMLFiberBundleStorageNodeTest1
      Start  5: vtkMRMLFiberBundleGlyphDisplayNodeTest1
32/54 Test  #5: vtkMRMLFiberBundleGlyphDisplayNodeTest1 ...............................   Passed    0.30 sec
      Start 38: FiberTractMeasurementsTestScalarOnlyFolder
33/54 Test #19: DWIToDTIEstimationTest ................................................   Passed    0.51 sec
34/54 Test  #8: vtkMRMLFiberBundleStorageNodeTest1 ....................................   Passed    0.30 sec
      Start  9: vtkMRMLFiberBundleTubeDisplayNodeTest1
      Start 47: FiberBundleLabelSelectCompareVTPTest
35/54 Test #38: FiberTractMeasurementsTestScalarOnlyFolder ............................   Passed    0.40 sec
36/54 Test #47: FiberBundleLabelSelectCompareVTPTest ..................................   Passed    0.20 sec
      Start 45: FiberBundleLabelSelectCompareVTKTest
      Start 40: FiberTractMeasurementsCompareTxtsHierarchy
37/54 Test  #9: vtkMRMLFiberBundleTubeDisplayNodeTest1 ................................   Passed    0.23 sec
38/54 Test #45: FiberBundleLabelSelectCompareVTKTest ..................................   Passed    0.03 sec
39/54 Test #40: FiberTractMeasurementsCompareTxtsHierarchy ............................   Passed    0.13 sec
      Start 39: FiberTractMeasurementsCompareTxtsFolder
      Start 41: FiberTractMeasurementsCompareTxtsHierarchyAllStatistics
      Start 42: FiberTractMeasurementsCompareTxtsScalarOnlyFolder
40/54 Test #39: FiberTractMeasurementsCompareTxtsFolder ...............................   Passed    0.01 sec
41/54 Test #42: FiberTractMeasurementsCompareTxtsScalarOnlyFolder .....................   Passed    0.11 sec
42/54 Test #41: FiberTractMeasurementsCompareTxtsHierarchyAllStatistics ...............   Passed    0.11 sec
43/54 Test #15: qSlicerTractographyInteractiveSeedingModuleGenericTest ................   Passed    7.51 sec
      Start 10: py_NsgPlanTracto
44/54 Test #10: py_NsgPlanTracto ......................................................   Passed   26.37 sec
      Start 11: py_DTINotReproducibleIssue3977
45/54 Test #11: py_DTINotReproducibleIssue3977 ........................................   Passed   21.54 sec
      Start 13: py_test_tractography_display
46/54 Test #13: py_test_tractography_display ..........................................   Passed   23.99 sec
      Start 14: py_SlicerMRBTest
47/54 Test #14: py_SlicerMRBTest ......................................................   Passed   41.06 sec
      Start 12: py_fiber_visibility_crash2438
48/54 Test #12: py_fiber_visibility_crash2438 .........................................   Passed   15.32 sec
      Start 52: py_TractographyExportPLY
49/54 Test #52: py_TractographyExportPLY ..............................................   Passed    4.85 sec
      Start 54: py_TractographyDownsample
50/54 Test #54: py_TractographyDownsample .............................................   Passed   14.13 sec
      Start 51: py_nomainwindow_qSlicerTractographyExportPLYModuleGenericTest
51/54 Test #51: py_nomainwindow_qSlicerTractographyExportPLYModuleGenericTest .........   Passed    4.63 sec
      Start 50: py_nomainwindow_qSlicerFiberBundleToLabelMapModuleGenericTest
52/54 Test #50: py_nomainwindow_qSlicerFiberBundleToLabelMapModuleGenericTest .........   Passed    4.58 sec
      Start 53: py_nomainwindow_qSlicerTractographyDownsampleModuleGenericTest
53/54 Test #53: py_nomainwindow_qSlicerTractographyDownsampleModuleGenericTest ........   Passed    5.22 sec
      Start 49: py_nomainwindow_qSlicerDICOM2FullBrainTractographyModuleGenericTest
54/54 Test #49: py_nomainwindow_qSlicerDICOM2FullBrainTractographyModuleGenericTest ...   Passed    4.91 sec

100% tests passed, 0 tests failed out of 54

Label Time Summary:
DWIToDTIEstimation                             =   0.51 sec*proc (1 test)
DiffusionTensorScalarMeasurements              =   6.46 sec*proc (14 tests)
DiffusionWeightedVolumeMasking                 =   0.50 sec*proc (1 test)
FiberBundleLabelSelect                         =   1.06 sec*proc (4 tests)
FiberTractMeasurements                         =   1.66 sec*proc (8 tests)
TractographyLabelMapSeeding                    =   0.36 sec*proc (1 test)
qSlicerTractographyDisplayModule               =  10.00 sec*proc (9 tests)
qSlicerTractographyInteractiveSeedingModule    =  20.99 sec*proc (4 tests)

Total Test time (real) = 179.96 sec
```

**Comment by ljod** [comment]
Amazing thank you!!!

**Comment by zhangfanmark** [comment]
Thank you, @jcfr ! Just successfully built SlicerDMRI from your branch using the Slicer-04-22 build, @ljod . 


Regards,
Fan

**Comment by zhangfanmark** [comment]
@ljod Also I noticed that there is a 'SlicerWithSlicerDMRI' inside the inner-build of SlicerDMRI. This one opens the "TK" logo (we saw together last time), and Slicer with SlicerDMRI.

**Comment by zhangfanmark** [comment]
Also compiled SlicerDcm2nii successfully, @ljod .

**Comment by ljod** [comment]
Thanks Fan! Before I merge these please test the compiled modules work for you.

**Comment by jcfr** [comment]
> Also I noticed that there is a 'SlicerWithSlicerDMRI' inside the inner-build of SlicerDMRI.  This one opens the "TK" logo (we saw together last time)

What does this mean ? Could you post a screenshot ?

**Comment by zhangfanmark** [comment]
When I clicked this "SlicerWithSlicerDMRI", it shows this "TK" logo, then a Slicer with SlicerDRI is opened (I don't need to do any installation or adding path to the extension.) @jcfr

**Comment by zhangfanmark** [comment]
Hi @ljod  seems working well for me. See some figures attached.

Screen Shot 2019-04-23 at 12 01 17 PM
Screen Shot 2019-04-23 at 12 01 04 PM

**Comment by ljod** [comment]
Thank you @jcfr and @zhangfanmark!!!

**Comment by jcfr** [comment]
> re: Tk logo 

I see. This is expected, this launcher is a convenience for the developer and we didn't setup icon update.

**Pull request merged**
