### PR TITLE
ENH: use line display as default

### LINKED ISSUE #98: Default Tube tract slows down tract display
Hi!

Displaying tube makes Slicer very slow when loading whole brain tractography (I tried one with only about 10k fibers). Why did we change the default display from Line to Tube? 

Thanks!

Fan

### PR DESCRIPTION
**Pull request by ihnorton**
Would fix #98

### CODE REVIEW

**Comment by ljod** [comment]
Looks good. What is the default color now for the lines?

**Comment by ihnorton** [comment]
> What is the default color now for the lines?

https://github.com/SlicerDMRI/SlicerDMRI/blob/e582d453d318a9ca235b36ea9c5a1670e0aaa4f0/Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleDisplayNode.cxx#L52

It looks like:

image

**Comment by ljod** [comment]
Yes I have always thought that color was not ideal. Is this the default display, or does it default to RGB directionally encoded color by orientation?

**Comment by ihnorton** [comment]
The current default is color-by-scalar, using FA. But the node falls back to solid if there are no tensors attached to the polydata. I'll change it to fall back to orientation.

**Comment by ljod** [comment]
sounds good. Also suggest updating the default color to something more palatable. What do you suggest? Perhaps a brighter yellow?

**Comment by ihnorton** [comment]
How about (255,247,10)

image

**Pull request merged**
