### PR TITLE
ENH: FBTractMeasurement: print only specified top cluster statistics by default.

### LINKED ISSUE #36: fiber tract scalar measurements appears not to preserve full hierarchy tree structure
To do statistics, it's appropriate to focus on one level, like for example subdivisions of the corpus callosum. The hierarchy has a tree structure that can have several levels. However when I read the measurements file into python, the name of each measurement seems to preserve only two levels of the hierarchy it is nested inside, instead of the unique full name. Here's an example from our tests. Looks like there is a possible CC with several levels inside it, and at each level only the current level and the parent are listed. In theory I could try to reconstruct the tree structure, but it would be much better for Slicer to output the full name including parents up to the root node that is being measured. 

['Possible CC', 'Possible CC:complete CC medial and later', 'Possible CC:nonhomologue', 'complete CC medial and later:region I', 'complete CC medial and later:region II', 'complete CC medial and later:region III', 'complete CC medial and later:region V', 'complete CC medial and later:region VI', 'nonhomologue:anterior', 'nonhomologue:mid', 'nonhomologue:posterior']

### PR DESCRIPTION
**Pull request by ihnorton**
Fixes #36.

### CODE REVIEW

**Comment by ihnorton** [comment]
The default behavior is now to print summary statistics only for the node specified with the single `--fiberHierarchy` argument. Note that the command must be run separately for each measured hierarchy node.

(the previous behavior is still available with `--printAllStatistics`)

**Comment by ljod** [comment]
Making sure I understand here. The goal is to print stats for the level of nodes immediately below the specified node. So if the node is the corpus, measure from its 5 subdivisions. Is that how this was implemented?

**Comment by ihnorton** [comment]
Right now it will measure from all subdivisions but only print the summary for the highest-level hierarchy node that is specified.

Do you want to print *only* the summaries for the subdivisions, or both the top node summary and the subdivisions? (and without any single-bundle stats in both cases)

**Comment by ljod** [comment]
I think people will most want the measurements from the subdivisions, and also may want it from the top node. So if the hierarchy is like this, people want measurements from CC1 to CC5 and definitely not the cluster leaf nodes. Possibly they want the measurement from the whole CC also, but it would be ok to not include it, so that it is clear that whatever is in the stats file is all from the same level, can be interpreted in the same way, and does not overlap.

CC
-- CC1
-- CC2
-- CC3
-- CC4
-- CC5

**Comment by ihnorton** [comment]
Ok. Implemented in #43.

Example output, for a scene with one top-level hierarchy ("Top1") which has two child nodes.

default:
```
Name 	 Num_Points 	 Num_Fibers 	 Hemisphere 	 Hemisphere.NAN 	 Subject_ID 	 Subject_ID.NAN
Top1 	 65762.000000 	 1298.000000 	 -0.038670 	 0.000000 	 4.080928 	 0.000000
Top1:Child1_1 	 24298.000000 	 421.000000 	 -0.049222 	 0.000000 	 4.092929 	 0.000000
Top1:Child1_2 	 20884.000000 	 440.000000 	 -0.193593 	 0.000000 	 3.783231 	 0.000000
```

`--printAllStatistics`:
```
Name 	 Num_Points 	 Num_Fibers 	 Hemisphere 	 Hemisphere.NAN 	 Subject_ID 	 Subject_ID.NAN
Top1:Child1_1:cluster_00005 	 6561.000000 	 153.000000 	 0.013565 	 0.000000 	 3.267032 	 0.000000
Top1:Child1_1:cluster_00007 	 2906.000000 	 65.000000 	 -0.386098 	 0.000000 	 5.013076 	 0.000000
Top1:Child1_1:cluster_00008 	 7994.000000 	 100.000000 	 0.000000 	 0.000000 	 5.190768 	 0.000000
Top1:Child1_1:cluster_00009 	 6837.000000 	 103.000000 	 -0.023841 	 0.000000 	 3.210765 	 0.000000
Top1:Child1_2:cluster_00003 	 8727.000000 	 200.000000 	 -0.015125 	 0.000000 	 3.474275 	 0.000000
Top1:Child1_2:cluster_00004 	 6145.000000 	 107.000000 	 -0.260212 	 0.000000 	 4.039219 	 0.000000
Top1:Child1_2:cluster_00006 	 6012.000000 	 133.000000 	 -0.384564 	 0.000000 	 3.970060 	 0.000000
Top1:cluster_00010 	 6788.000000 	 147.000000 	 -0.022687 	 0.000000 	 4.133471 	 0.000000
Top1:cluster_00011 	 4878.000000 	 99.000000 	 0.362854 	 0.000000 	 4.698852 	 0.000000
Top1:cluster_00012 	 8914.000000 	 191.000000 	 0.121158 	 0.000000 	 4.367512 	 0.000000
Top1 	 65762.000000 	 1298.000000 	 -0.038670 	 0.000000 	 4.080928 	 0.000000
Top1:Child1_1 	 24298.000000 	 421.000000 	 -0.049222 	 0.000000 	 4.092929 	 0.000000
Top1:Child1_2 	 20884.000000 	 440.000000 	 -0.193593 	 0.000000 	 3.783231 	 0.000000
```

**Pull request merged**
