### PR TITLE
ENH: Add testing cases for FiberTractMeasurement

### PR DESCRIPTION
**Pull request by zhangfanmark**
Add testing cases of VTK and VTP inputs for FiberTractMeasurement module.

Hi @ihnorton ,

Could you please take a look at this pull request? Thanks!
A double check of the added testing cases may be needed when the latest Slicer can be compiled with BUILD_TESTING on. 

Regards,
Fan

### CODE REVIEW

**Comment by ihnorton** [comment]
@zhangfanmark thanks, a couple comments:
- `Master Scene View.png` was checked-in, but probably does not need to be.
- the `baseline_measurements_folder.txt` file has a hard-coded path

**Comment by zhangfanmark** [comment]
Hi @ihnorton 

1) Yes, we can delete the png file. 
2) This module outputs the full path of input vtk/vtp. I have handled this in the code. So, when comparing the baseline and results, the test will skip the path. But, you are right, it better to remove the hard-coded path. I'll update the files later. 

Thanks,
Fan

**Comment by ljod** [comment]
Hi guys is this finished? Can we accept this pull request?

**Comment by ihnorton** [comment]
Committed in 50b0294300459f318ab01363c3ed6819336c8b50. Thanks!

**Pull request closed without merging**
