### PR TITLE
Update README.md to test rebuild

### PR DESCRIPTION
**Pull request by pieper**
Small change to see if a new package becomes available for the 5.6.1 release of Slicer.

See: https://github.com/Slicer/Slicer/issues/7531

### CODE REVIEW

**Comment by pieper** [comment]
It would be great if one of you could review today and then check if a new build is generated tomorrow.

**Review by jhlegarreta — APPROVED** [review]
It might be a good opportunity to find/replace all the instances that were left behind in PR https://github.com/SlicerDMRI/SlicerDMRI/pull/229, and that were still causing issues as reported in an email thread.

Otherwise, if this PR needs to be merged, once the rebuild test is checked tomorrow, I would push force to the immediately previous commit to avoid a test commit being part of the history of the `master`  branch.

Already late in here (+6 hours) so feel free to decide on the above options. Thanks.

**Comment by pieper** [comment]
I think it's fine to take these one at a time.  Having a few extra test commits in the history doesn't bother me but force-pushes are always a concern (even though we don't have a lot of activity in this repository they are not a good thing in general).

We should certainly keep working on fixing any issues like the ONe in #229 and also confirm that we are getting them out into the actual published extension for the intended versions.

**Comment by jhlegarreta** [comment]
> Having a few extra test commits in the history doesn't bother me but force-pushes are always a concern

It becomes a concern when trying to understand why some changes were introduced. We both agree that this commit is an experiment to test something in 3D Slicer's extension update mechanism. So the force-push is certainly justified in this case. I will take care of it, no worries.

> also confirm that we are getting them out into the actual published extension for the intended versions

Unless the update policy matches the 3D Slicer expectation (documenting it would be great), there is probably an additional measure that can be taken (e.g. a test) that can be done in 3D Slicer proper to ensure this (e.g. check that the commit hash of the extension, as provided by the information that can be retrieved from the `*.ext` file, matches to what 3D Slicer effectively fetches); i.e. the concern applies to all extensions.

**Pull request merged**
