### PR TITLE
ENH: Update extension metadata

### PR DESCRIPTION
**Pull request by jcfr**
Consolidate extension metadata based on the corresponding s4ext file organized
in the ExtensionsIndex repository.

### CODE REVIEW

**Comment by jcfr** [comment]
Please, could this be reviewed & merged :pray: 

cc: @jhlegarreta @ljod @pieper

**Comment by jcfr** [comment]
Email sent on June 12th 2024 to @pieper, @ljod and @jhlegarreta  with @lassoan in cc:

```
Subject: Help to merge https://github.com/SlicerDMRI/SlicerDMRI/pull/235

Hi Team,

When you have a chance, we would appreciate your help to merge the following pull request:

  ENH: Update extension metadata
  https://github.com/SlicerDMRI/SlicerDMRI/pull/235

Changes are trivial as they only include updates to the extension metadata.

Thanks
J-Christophe
```

**Review by ljod — APPROVED** [review]
Looks nice thanks for improving this!

**Comment by jcfr** [comment]
@ljod  Thanks for taking the time to follow-up :pray: :rocket:

**Pull request merged**
