### PR TITLE
STYLE: Prefer using f-strings

### PR DESCRIPTION
**Pull request by jhlegarreta**
Prefer using f-strings.

### CODE REVIEW

**Review by pieper — COMMENTED** [review]
@jhlegarreta it would be nice to think about preparing SlicerDMRI for internationalization.  I don't think we have a developer guide for this yet, but one aspect is that we are using `.format` instead of f-strings (e.g. like [this](https://github.com/Slicer/Slicer/blob/eccb98ce1f58b19d0a429981cc8e3cf131bcf3d5/Modules/Scripted/DICOMLib/DICOMBrowser.py#L427)).  The reason is that if we used f-strings then translations of that string could introduce arbitrary code which would be a security issue.

Although I like f-strings generally, I think we should try to make the code ready for i18n.

**Comment by jhlegarreta** [comment]
>  The reason is that if we used f-strings then translations of that string could introduce arbitrary code which would be a security issue.

Do you know whether the Python folks are investigating this pitfall on f-strings while being used for i18n?

If they are, that would be excellent, and would give more value to this PR.

Otherwise, TBH, it would be a very low priority task for me to use the `.format()` string formatting model: the toolkit has other more fundamental issues or needs IMO.

On a slightly related note, the CI builds logs are full of traces related to internationalization, e.g.
https://github.com/SlicerDMRI/SlicerDMRI/actions/runs/7051428476/job/19194285977?pr=198#step:6:26037

Seem to be warnings related to 3D Slicer or CTK, stemming from some Qt deprecation. It may be worthwhile to address those to avoid a visual pollution that prevents from identifying other warnings.

And this happens despite telling CMake not to build 3D Slicer with i18n support:
https://github.com/SlicerDMRI/SlicerDMRI/blob/master/.github/workflows/build-test.yml#L65

**Comment by pieper** [comment]
> Do you know whether the Python folks are investigating this pitfall on f-strings while being used for i18n?

I have no idea.  Probably the correct thing is to parse the f-string and only present the actual text for translation.



> On a slightly related note, the CI builds logs are full of traces related to internationalization, e.g. https://github.com/SlicerDMRI/SlicerDMRI/actions/runs/7051428476/job/19194285977?pr=198#step:6:26037

Can you point to a specific example or two?  This log is huge and barely loads.  The internationalization support is still new, so it's not a surprise that there are still some issues to resolve.

**Comment by lassoan** [comment]
We don't do anything special for i18n in Slicer, just use translation functions in a very simple, straightforward way. The build warnings are probably due to PythonQt and you can safely ignore it. PythonQt developers don't aim for warning-free code on all compilers. I would prefer if they tried a bit harder but it's an open-source library, so I guess anybody who is bothered could submit a pull request to fix warnings. You may try to use the latest Qt5 version, maybe it helps.

Python's recommendation is to use named placeholders in translatable text. Python's core translation infrastructure (gettext) does not support f-strings at all. Our infrastructure could take f-strings, but it would be unsafe.

Note that messages for developers must not be translated (it would make debugging much harder and unnecessarily increase translation workload), so you can keep using any string functions for messages that are only shown to developers. It could make sense to use `print` function for messages that are intended for end users and logging functions for messages for developers.

**Comment by jhlegarreta** [comment]
> We don't do anything special for i18n in Slicer, just use translation functions in a very simple, straightforward way. The build warnings are probably due to PythonQt and you can safely ignore it. PythonQt developers don't aim for warning-free code on all compilers. I would prefer if they tried a bit harder but it's an open-source library, so I guess anybody who is bothered could submit a pull request to fix warnings. You may try to use the latest Qt5 version, maybe it helps.

Yes, the warnings look harmless, but they are polluting the logs and the builds in important ways, and prevent to navigate through them and to easily locate potentially harmful warnings.

Even more so when we have instructed CMake not use i18n _at all_:
```
          -DSlicer_BUILD_I18N_SUPPORT:BOOL=OFF \
```
https://github.com/SlicerDMRI/SlicerDMRI/blob/master/.github/workflows/build-test.yml#L65

> Note that messages for developers must not be translated (it would make debugging much harder and unnecessarily increase translation workload), so you can keep using any string functions for messages that are only shown to developers. It could make sense to use print function for messages that are intended for end users and logging functions for messages for developers.

I agree; a proper logging system should be in place. However, this is a low priority now. And of course, I do not aim at translating any logged message; i18n is even a low priority for the toolkit in its current state.

**Comment by jhlegarreta** [comment]
The warning comes from Qt 5.15.2:
https://github.com/CipSoft-Tibia/Qt5/blob/40f5aa5ff6f981ecd2403c70dd2419dfd9ae4d0b/qtbase/src/corelib/text/qlocale.h#L941

Qt 5.12.11 still has it:
https://github.com/qt/qtbase/blob/5.15/src/corelib/text/qlocale.h#L941

The first release removing the warning is 6.0.0. Does 3D Slicer support Qt 6.0.x @lassoan @jcfr ?

**Comment by jhlegarreta** [comment]
Well aware of all the above; the issue is inspecting the CI builds.

> Qt6 must be https://github.com/MeVisLab/pythonqt/issues/13 and https://github.com/commontk/CTK/issues/947. Probably it will happen sometime in 2024.

OK. Thanks.

**Review by ljod — APPROVED** [review]

**Comment by jhlegarreta** [comment]
> Qt6 must be supported first by PythonQt and CTK. Probably it will happen sometime in 2024.

@lassoan Looks like there starts to be some alpha releases for Qt6 in PythonQt:
https://github.com/MeVisLab/pythonqt/issues/13#issuecomment-1857470843
https://github.com/MeVisLab/pythonqt/tags

**Comment by lassoan** [comment]
Yes, thanks for the ping, it seems that @jamesobutler has already started looking into it.

**Pull request merged**
